# Generated by Django 4.2.2 on 2023-06-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_episode_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="media_type",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
