# Generated by Django 4.2.2 on 2023-06-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0003_alter_show_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="number",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
