# Generated by Django 4.2.2 on 2023-06-28 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0004_season_number"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="updateque",
            table=None,
        ),
    ]
