# Generated by Django 4.2.2 on 2023-07-07 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0005_alter_updateque_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="air_date",
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 4, 47, 5, 765895)),
            preserve_default=False,
        ),
    ]
