# Generated by Django 4.2.2 on 2023-07-24 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0007_episode_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="thumbnail_url",
        ),
    ]
