# Generated by Django 4.2.2 on 2023-09-02 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0009_remove_season_image_url_remove_season_thumbnail_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="season",
            name="number",
        ),
    ]
