# Generated by Django 4.2.2 on 2023-09-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0010_remove_season_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="number",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
