# Generated by Django 5.0.1 on 2024-03-27 03:25

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0013_alter_episode_options_alter_episodewatch_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, null=True, upload_to="images"
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, null=True, upload_to="images"
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, null=True, upload_to="images"
            ),
        ),
    ]
