# Generated by Django 5.0.3 on 2024-03-29 04:01

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0014_alter_episode_image_alter_season_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="show",
            name="favicon_url",
        ),
        migrations.AddField(
            model_name="show",
            name="favicon",
            field=sorl.thumbnail.fields.ImageField(
                default=1, max_length=255, upload_to=""
            ),
            preserve_default=False,
        ),
    ]
