# Generated by Django 5.0.3 on 2024-03-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0015_remove_show_favicon_url_show_favicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="media_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="show",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="updateque",
            name="website",
            field=models.CharField(max_length=255),
        ),
    ]
