# Generated by Django 5.0.3 on 2024-03-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0017_season_update_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="update_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
