# Generated by Django 4.0 on 2022-01-01 04:27

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0002_alter_episode_options_and_more"),
        ("playlists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistshow",
            name="season_skip",
            field=models.ManyToManyField(through="playlists.PlaylistSeasonSkip", to="shows.Season"),
        ),
    ]
