# Generated by Django 4.0 on 2022-01-11 00:20

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0002_alter_episode_options_and_more"),
        ("playlists", "0002_playlistshow_season_skip"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlaylistSeasonSkip",
            new_name="PlaylistSeason",
        ),
        migrations.RemoveField(
            model_name="playlistshow",
            name="season_skip",
        ),
        migrations.AddField(
            model_name="playlistshow",
            name="season_to_skip",
            field=models.ManyToManyField(through="playlists.PlaylistSeason", to="shows.Season"),
        ),
    ]
