# Generated by Django 4.0 on 2022-01-11 00:23

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0003_rename_playlistseasonskip_playlistseason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistseason",
            name="skip",
            field=models.BooleanField(default=False),
        ),
    ]
