# Generated by Django 4.0 on 2022-01-18 10:01

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0004_playlistseason_skip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlistshow",
            old_name="season_to_skip",
            new_name="playlist_season",
        ),
    ]
