# Generated by Django 4.0.1 on 2022-01-31 02:58

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0005_rename_season_to_skip_playlistshow_playlist_season"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlaylistImportQue",
            new_name="PlaylistImportQueue",
        ),
    ]
