# Generated by Django 4.2.2 on 2023-06-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("default_filter", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "playlist",
            },
        ),
        migrations.CreateModel(
            name="PlaylistSeason",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("skip", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PlaylistShow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("playlist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="playlists.playlist")),
                ("playlist_season", models.ManyToManyField(through="playlists.PlaylistSeason", to="media.season")),
                ("show", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="media.show")),
            ],
        ),
        migrations.AddField(
            model_name="playlistseason",
            name="playlist_show",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="playlists.playlistshow"),
        ),
        migrations.AddField(
            model_name="playlistseason",
            name="season",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="media.season"),
        ),
        migrations.CreateModel(
            name="PlaylistImportQueue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=256)),
                ("playlist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="playlists.playlist")),
            ],
        ),
        migrations.AddField(
            model_name="playlist",
            name="shows",
            field=models.ManyToManyField(through="playlists.PlaylistShow", to="media.show"),
        ),
        migrations.AddConstraint(
            model_name="playlistshow",
            constraint=models.UniqueConstraint(fields=("show", "playlist"), name="PlaylistShow_show_playlist"),
        ),
        migrations.AddConstraint(
            model_name="playlistseason",
            constraint=models.UniqueConstraint(
                fields=("playlist_show", "season"), name="PlaylistSeason_playlist_show_season"
            ),
        ),
        migrations.AddConstraint(
            model_name="playlistimportqueue",
            constraint=models.UniqueConstraint(fields=("playlist", "url"), name="PlaylistImportQueue_playlist_url"),
        ),
    ]
