# Generated by Django 4.2.2 on 2023-06-09 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0002_alter_playlist_options_playlist_deleted"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="playlist",
            table=None,
        ),
    ]
