# Generated by Django 4.2.2 on 2023-06-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0003_alter_playlist_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="default_filter",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
