# Generated by Django 4.2.2 on 2023-06-13 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0004_alter_playlist_default_filter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlistshow",
            name="playlist_season",
        ),
        migrations.DeleteModel(
            name="PlaylistSeason",
        ),
    ]
