# Generated by Django 4.2.2 on 2023-06-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0006_playlist_thumbnail_alter_playlist_default_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="thumbnail",
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to="static/thumbnails"),
        ),
    ]
