# Generated by Django 4.2.2 on 2023-07-24 10:43

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0007_alter_playlist_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="thumbnail",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, default=None, max_length=255, null=True, upload_to="static/thumbnails"
            ),
        ),
    ]
