# Generated by Django 5.0.1 on 2024-03-27 03:28

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "playlists",
            "0009_remove_playlistimportqueue_playlistimportqueue_playlist_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="thumbnail",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, null=True, upload_to="images"
            ),
        ),
    ]
