# Generated by Django 5.0.3 on 2024-03-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0010_alter_playlist_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistimportqueue",
            name="url",
            field=models.CharField(max_length=255),
        ),
    ]
