# Generated by Django 5.0.3 on 2024-03-29 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0011_alter_playlistimportqueue_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playlist",
            options={"ordering": ("name",)},
        ),
    ]
