# Generated by Django 4.0 on 2021-12-21 10:56

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                ("episode_id", models.CharField(max_length=64)),
                ("image_url", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("release_date", models.DateTimeField(null=True)),
                ("sort_id", models.PositiveSmallIntegerField()),
                ("number", models.CharField(max_length=64)),
                ("info_timestamp", models.DateTimeField()),
                ("info_modified_timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "episode",
                "ordering": ["sort_id"],
            },
        ),
        migrations.CreateModel(
            name="EpisodeWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watch_date", models.DateField()),
            ],
            options={
                "db_table": "episode_watch",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=500)),
                ("number", models.PositiveSmallIntegerField()),
                ("season_id", models.CharField(max_length=64)),
                ("image_url", models.CharField(max_length=255)),
                ("info_timestamp", models.DateTimeField()),
                ("info_modified_timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "season",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("website", models.CharField(max_length=64)),
                ("show_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("image_url", models.CharField(max_length=256)),
                ("info_timestamp", models.DateTimeField()),
                ("info_modified_timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "show",
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="show",
            constraint=models.UniqueConstraint(fields=("website", "show_id"), name="website show"),
        ),
        migrations.AddField(
            model_name="season",
            name="show",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shows.show"),
        ),
        migrations.AddField(
            model_name="episodewatch",
            name="episode",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shows.episode"),
        ),
        migrations.AddField(
            model_name="episode",
            name="season",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shows.season"),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(fields=("show", "season_id"), name="show_season_id"),
        ),
        migrations.AddConstraint(
            model_name="episode",
            constraint=models.UniqueConstraint(fields=("season", "episode_id"), name="season_episode_id"),
        ),
    ]
