# Generated by Django 4.0 on 2022-01-01 01:57

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episode",
            options={"ordering": ["sort_order"]},
        ),
        migrations.RenameField(
            model_name="episode",
            old_name="sort_id",
            new_name="sort_order",
        ),
    ]
