# Generated by Django 4.0 on 2022-01-19 10:22

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0002_alter_episode_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="image_url",
            new_name="image_id",
        ),
        migrations.RenameField(
            model_name="season",
            old_name="image_url",
            new_name="image_id",
        ),
        migrations.RenameField(
            model_name="show",
            old_name="image_url",
            new_name="image_id",
        ),
    ]
