# Generated by Django 4.0 on 2022-01-19 10:28

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0003_rename_image_url_episode_image_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="image_id",
            new_name="image_url",
        ),
        migrations.RenameField(
            model_name="season",
            old_name="image_id",
            new_name="image_url",
        ),
        migrations.RenameField(
            model_name="show",
            old_name="image_id",
            new_name="image_url",
        ),
        migrations.AddField(
            model_name="episode",
            name="thumbnail_url",
            field=models.CharField(default="MISSING", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="thumbnail_url",
            field=models.CharField(default="MISSING", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="show",
            name="thumbnail_url",
            field=models.CharField(default="MISSING", max_length=255),
            preserve_default=False,
        ),
    ]
