# Generated by Django 4.0.1 on 2022-01-22 04:41

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0004_rename_image_id_episode_image_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episodewatch",
            options={"ordering": ["watch_date"]},
        ),
        migrations.RemoveConstraint(
            model_name="episode",
            name="season_episode_id",
        ),
        migrations.RemoveConstraint(
            model_name="season",
            name="show_season_id",
        ),
        migrations.RemoveConstraint(
            model_name="show",
            name="website show",
        ),
        migrations.AddConstraint(
            model_name="episode",
            constraint=models.UniqueConstraint(fields=("season", "episode_id"), name="season__episode_id"),
        ),
        migrations.AddConstraint(
            model_name="episodewatch",
            constraint=models.UniqueConstraint(fields=("episode", "watch_date"), name="episode__watch_date"),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(fields=("show", "season_id"), name="show__season_id"),
        ),
        migrations.AddConstraint(
            model_name="show",
            constraint=models.UniqueConstraint(fields=("website", "show_id"), name="website__show_id"),
        ),
    ]
