# Generated by Django 4.0.1 on 2022-01-22 04:42

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0005_alter_episodewatch_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="episodewatch",
            name="episode__watch_date",
        ),
    ]
