# Generated by Django 4.0.1 on 2022-01-28 07:54

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0006_remove_episodewatch_episode__watch_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="length",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="episode",
            name="sort_order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="episodewatch",
            constraint=models.UniqueConstraint(fields=("episode", "watch_date"), name="episode__watch_date"),
        ),
    ]
