# Generated by Django 4.0.1 on 2022-01-28 07:55

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0007_episode_length_alter_episode_sort_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="length",
            new_name="duration",
        ),
    ]
