# Generated by Django 4.0.1 on 2022-01-30 06:15

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0008_rename_length_episode_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="sort_order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
