# Generated by Django 4.0.1 on 2022-01-30 06:17

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0009_season_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="number",
            field=models.CharField(max_length=255),
        ),
    ]
