# Generated by Django 4.0.1 on 2022-01-31 02:58

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0010_alter_season_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episode",
            options={"ordering": ["season", "sort_order"]},
        ),
        migrations.AlterModelOptions(
            name="season",
            options={"ordering": ["show", "sort_order"]},
        ),
    ]
