# Generated by Django 4.0.1 on 2022-03-28 04:45

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0011_alter_episode_options_alter_season_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="show_id_2",
            field=models.CharField(default="WILL BE FIXED", max_length=64),
            preserve_default=False,
        ),
    ]
