# Generated by Django 4.0.1 on 2022-03-28 05:14

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0012_show_show_id_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="show_id_2",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="show",
            constraint=models.UniqueConstraint(fields=("website", "show_id_2"), name="website__show_id_2"),
        ),
    ]
