# Generated by Django 4.0.1 on 2022-03-28 05:15

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0013_alter_show_show_id_2_show_website__show_id_2"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="show",
            name="website__show_id_2",
        ),
    ]
