# Generated by Django 4.0.3 on 2022-05-06 07:20

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0014_remove_show_website__show_id_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="update_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="release_date",
            field=models.DateTimeField(),
        ),
    ]
