# Generated by Django 4.0.4 on 2022-05-14 22:33

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0017_alter_show_update_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="update_at",
            field=models.DateTimeField(null=True),
        ),
    ]
