# Generated by Django 4.0.4 on 2022-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0018_alter_show_update_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='episode',
            name='season__episode_id',
        ),
        migrations.RemoveConstraint(
            model_name='episodewatch',
            name='episode__watch_date',
        ),
        migrations.RemoveConstraint(
            model_name='season',
            name='show__season_id',
        ),
        migrations.RemoveConstraint(
            model_name='show',
            name='website__show_id',
        ),
        migrations.AddField(
            model_name='show',
            name='media_type',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'episode_id')},
        ),
        migrations.AlterUniqueTogether(
            name='episodewatch',
            unique_together={('episode', 'watch_date')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('show', 'season_id')},
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('website', 'show_id'), ('website', 'show_id_2')},
        ),
    ]
