# Generated by Django 4.0.4 on 2022-07-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0019_remove_episode_season__episode_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_id',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='show_id_2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
