# Generated by Django 4.0.4 on 2022-07-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0020_alter_show_show_id_alter_show_show_id_2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='episodewatch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('season', 'episode_id'), name='season_episode_id'),
        ),
        migrations.AddConstraint(
            model_name='episodewatch',
            constraint=models.UniqueConstraint(fields=('episode', 'watch_date'), name='episode_watch_date'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('show', 'season_id'), name='show_season_id'),
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('website', 'show_id'), name='website__show_id'),
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('website', 'show_id_2'), name='website_show_id_2'),
        ),
    ]
