# Generated by Django 4.0.4 on 2022-07-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0021_alter_episode_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='episode',
            name='season_episode_id',
        ),
        migrations.RemoveConstraint(
            model_name='episodewatch',
            name='episode_watch_date',
        ),
        migrations.AddField(
            model_name='episode',
            name='cross_referenced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('season', 'episode_id'), name='Episode_season_episode_id'),
        ),
        migrations.AddConstraint(
            model_name='episodewatch',
            constraint=models.UniqueConstraint(fields=('episode', 'watch_date'), name='EpisodeWatch_episode_watch_date'),
        ),
    ]
